const elementsData = [
  { num: 1, symbol: "H", name: "Hydrogen", mass: "1.008", category: "nonmetal", x: 1, y: 1, config: "1s1", desc: "Hydrogen is the chemical element with the symbol H and atomic number 1." },
  { num: 2, symbol: "He", name: "Helium", mass: "4.0026", category: "noble-gas", x: 18, y: 1, config: "1s2", desc: "Helium is a chemical element with the symbol He and atomic number 2." },
  { num: 3, symbol: "Li", name: "Lithium", mass: "6.94", category: "alkali-metal", x: 1, y: 2, config: "[He] 2s1", desc: "Lithium is a chemical element with the symbol Li and atomic number 3." },
  { num: 4, symbol: "Be", name: "Beryllium", mass: "9.0122", category: "alkaline-earth", x: 2, y: 2, config: "[He] 2s2", desc: "Beryllium is a chemical element with the symbol Be and atomic number 4." },
  { num: 5, symbol: "B", name: "Boron", mass: "10.81", category: "metalloid", x: 13, y: 2, config: "[He] 2s2 2p1", desc: "Boron is a chemical element with the symbol B and atomic number 5." },
  { num: 6, symbol: "C", name: "Carbon", mass: "12.011", category: "nonmetal", x: 14, y: 2, config: "[He] 2s2 2p2", desc: "Carbon is a chemical element with the symbol C and atomic number 6." },
  { num: 7, symbol: "N", name: "Nitrogen", mass: "14.007", category: "nonmetal", x: 15, y: 2, config: "[He] 2s2 2p3", desc: "Nitrogen is the chemical element with the symbol N and atomic number 7." },
  { num: 8, symbol: "O", name: "Oxygen", mass: "15.999", category: "nonmetal", x: 16, y: 2, config: "[He] 2s2 2p4", desc: "Oxygen is the chemical element with the symbol O and atomic number 8." },
  { num: 9, symbol: "F", name: "Fluorine", mass: "18.998", category: "halogen", x: 17, y: 2, config: "[He] 2s2 2p5", desc: "Fluorine is a chemical element with the symbol F and atomic number 9." },
  { num: 10, symbol: "Ne", name: "Neon", mass: "20.180", category: "noble-gas", x: 18, y: 2, config: "[He] 2s2 2p6", desc: "Neon is a chemical element with the symbol Ne and atomic number 10." },
  { num: 11, symbol: "Na", name: "Sodium", mass: "22.990", category: "alkali-metal", x: 1, y: 3, config: "[Ne] 3s1", desc: "Sodium is a chemical element with the symbol Na and atomic number 11." },
  { num: 12, symbol: "Mg", name: "Magnesium", mass: "24.305", category: "alkaline-earth", x: 2, y: 3, config: "[Ne] 3s2", desc: "Magnesium is a chemical element with the symbol Mg and atomic number 12." },
  { num: 13, symbol: "Al", name: "Aluminium", mass: "26.982", category: "post-transition", x: 13, y: 3, config: "[Ne] 3s2 3p1", desc: "Aluminium is a chemical element with the symbol Al and atomic number 13." },
  { num: 14, symbol: "Si", name: "Silicon", mass: "28.085", category: "metalloid", x: 14, y: 3, config: "[Ne] 3s2 3p2", desc: "Silicon is a chemical element with the symbol Si and atomic number 14." },
  { num: 15, symbol: "P", name: "Phosphorus", mass: "30.974", category: "nonmetal", x: 15, y: 3, config: "[Ne] 3s2 3p3", desc: "Phosphorus is a chemical element with the symbol P and atomic number 15." },
  { num: 16, symbol: "S", name: "Sulfur", mass: "32.06", category: "nonmetal", x: 16, y: 3, config: "[Ne] 3s2 3p4", desc: "Sulfur is a chemical element with the symbol S and atomic number 16." },
  { num: 17, symbol: "Cl", name: "Chlorine", mass: "35.45", category: "halogen", x: 17, y: 3, config: "[Ne] 3s2 3p5", desc: "Chlorine is a chemical element with the symbol Cl and atomic number 17." },
  { num: 18, symbol: "Ar", name: "Argon", mass: "39.948", category: "noble-gas", x: 18, y: 3, config: "[Ne] 3s2 3p6", desc: "Argon is a chemical element with the symbol Ar and atomic number 18." },
  { num: 19, symbol: "K", name: "Potassium", mass: "39.098", category: "alkali-metal", x: 1, y: 4, config: "[Ar] 4s1", desc: "Potassium is a chemical element with the symbol K and atomic number 19." },
  { num: 20, symbol: "Ca", name: "Calcium", mass: "40.078", category: "alkaline-earth", x: 2, y: 4, config: "[Ar] 4s2", desc: "Calcium is a chemical element with the symbol Ca and atomic number 20." },
  { num: 21, symbol: "Sc", name: "Scandium", mass: "44.956", category: "transition-metal", x: 3, y: 4, config: "[Ar] 3d1 4s2", desc: "Scandium is a chemical element with the symbol Sc and atomic number 21." },
  { num: 22, symbol: "Ti", name: "Titanium", mass: "47.867", category: "transition-metal", x: 4, y: 4, config: "[Ar] 3d2 4s2", desc: "Titanium is a chemical element with the symbol Ti and atomic number 22." },
  { num: 23, symbol: "V", name: "Vanadium", mass: "50.942", category: "transition-metal", x: 5, y: 4, config: "[Ar] 3d3 4s2", desc: "Vanadium is a chemical element with the symbol V and atomic number 23." },
  { num: 24, symbol: "Cr", name: "Chromium", mass: "51.996", category: "transition-metal", x: 6, y: 4, config: "[Ar] 3d5 4s1", desc: "Chromium is a chemical element with the symbol Cr and atomic number 24." },
  { num: 25, symbol: "Mn", name: "Manganese", mass: "54.938", category: "transition-metal", x: 7, y: 4, config: "[Ar] 3d5 4s2", desc: "Manganese is a chemical element with the symbol Mn and atomic number 25." },
  { num: 26, symbol: "Fe", name: "Iron", mass: "55.845", category: "transition-metal", x: 8, y: 4, config: "[Ar] 3d6 4s2", desc: "Iron is a chemical element with the symbol Fe and atomic number 26." },
  { num: 27, symbol: "Co", name: "Cobalt", mass: "58.933", category: "transition-metal", x: 9, y: 4, config: "[Ar] 3d7 4s2", desc: "Cobalt is a chemical element with the symbol Co and atomic number 27." },
  { num: 28, symbol: "Ni", name: "Nickel", mass: "58.693", category: "transition-metal", x: 10, y: 4, config: "[Ar] 3d8 4s2", desc: "Nickel is a chemical element with the symbol Ni and atomic number 28." },
  { num: 29, symbol: "Cu", name: "Copper", mass: "63.546", category: "transition-metal", x: 11, y: 4, config: "[Ar] 3d10 4s1", desc: "Copper is a chemical element with the symbol Cu and atomic number 29." },
  { num: 30, symbol: "Zn", name: "Zinc", mass: "65.38", category: "transition-metal", x: 12, y: 4, config: "[Ar] 3d10 4s2", desc: "Zinc is a chemical element with the symbol Zn and atomic number 30." },
  { num: 31, symbol: "Ga", name: "Gallium", mass: "69.723", category: "post-transition", x: 13, y: 4, config: "[Ar] 3d10 4s2 4p1", desc: "Gallium is a chemical element with the symbol Ga and atomic number 31." },
  { num: 32, symbol: "Ge", name: "Germanium", mass: "72.630", category: "metalloid", x: 14, y: 4, config: "[Ar] 3d10 4s2 4p2", desc: "Germanium is a chemical element with the symbol Ge and atomic number 32." },
  { num: 33, symbol: "As", name: "Arsenic", mass: "74.922", category: "metalloid", x: 15, y: 4, config: "[Ar] 3d10 4s2 4p3", desc: "Arsenic is a chemical element with the symbol As and atomic number 33." },
  { num: 34, symbol: "Se", name: "Selenium", mass: "78.971", category: "nonmetal", x: 16, y: 4, config: "[Ar] 3d10 4s2 4p4", desc: "Selenium is a chemical element with the symbol Se and atomic number 34." },
  { num: 35, symbol: "Br", name: "Bromine", mass: "79.904", category: "halogen", x: 17, y: 4, config: "[Ar] 3d10 4s2 4p5", desc: "Bromine is a chemical element with the symbol Br and atomic number 35." },
  { num: 36, symbol: "Kr", name: "Krypton", mass: "83.798", category: "noble-gas", x: 18, y: 4, config: "[Ar] 3d10 4s2 4p6", desc: "Krypton is a chemical element with the symbol Kr and atomic number 36." },
  { num: 37, symbol: "Rb", name: "Rubidium", mass: "85.468", category: "alkali-metal", x: 1, y: 5, config: "[Kr] 5s1", desc: "Rubidium is a chemical element with the symbol Rb and atomic number 37." },
  { num: 38, symbol: "Sr", name: "Strontium", mass: "87.62", category: "alkaline-earth", x: 2, y: 5, config: "[Kr] 5s2", desc: "Strontium is a chemical element with the symbol Sr and atomic number 38." },
  { num: 39, symbol: "Y", name: "Yttrium", mass: "88.906", category: "transition-metal", x: 3, y: 5, config: "[Kr] 4d1 5s2", desc: "Yttrium is a chemical element with the symbol Y and atomic number 39." },
  { num: 40, symbol: "Zr", name: "Zirconium", mass: "91.224", category: "transition-metal", x: 4, y: 5, config: "[Kr] 4d2 5s2", desc: "Zirconium is a chemical element with the symbol Zr and atomic number 40." },
  { num: 41, symbol: "Nb", name: "Niobium", mass: "92.906", category: "transition-metal", x: 5, y: 5, config: "[Kr] 4d4 5s1", desc: "Niobium is a chemical element with the symbol Nb and atomic number 41." },
  { num: 42, symbol: "Mo", name: "Molybdenum", mass: "95.95", category: "transition-metal", x: 6, y: 5, config: "[Kr] 4d5 5s1", desc: "Molybdenum is a chemical element with the symbol Mo and atomic number 42." },
  { num: 43, symbol: "Tc", name: "Technetium", mass: "(98)", category: "transition-metal", x: 7, y: 5, config: "[Kr] 4d5 5s2", desc: "Technetium is a chemical element with the symbol Tc and atomic number 43." },
  { num: 44, symbol: "Ru", name: "Ruthenium", mass: "101.07", category: "transition-metal", x: 8, y: 5, config: "[Kr] 4d7 5s1", desc: "Ruthenium is a chemical element with the symbol Ru and atomic number 44." },
  { num: 45, symbol: "Rh", name: "Rhodium", mass: "102.91", category: "transition-metal", x: 9, y: 5, config: "[Kr] 4d8 5s1", desc: "Rhodium is a chemical element with the symbol Rh and atomic number 45." },
  { num: 46, symbol: "Pd", name: "Palladium", mass: "106.42", category: "transition-metal", x: 10, y: 5, config: "[Kr] 4d10", desc: "Palladium is a chemical element with the symbol Pd and atomic number 46." },
  { num: 47, symbol: "Ag", name: "Silver", mass: "107.87", category: "transition-metal", x: 11, y: 5, config: "[Kr] 4d10 5s1", desc: "Silver is a chemical element with the symbol Ag and atomic number 47." },
  { num: 48, symbol: "Cd", name: "Cadmium", mass: "112.41", category: "transition-metal", x: 12, y: 5, config: "[Kr] 4d10 5s2", desc: "Cadmium is a chemical element with the symbol Cd and atomic number 48." },
  { num: 49, symbol: "In", name: "Indium", mass: "114.82", category: "post-transition", x: 13, y: 5, config: "[Kr] 4d10 5s2 5p1", desc: "Indium is a chemical element with the symbol In and atomic number 49." },
  { num: 50, symbol: "Sn", name: "Tin", mass: "118.71", category: "post-transition", x: 14, y: 5, config: "[Kr] 4d10 5s2 5p2", desc: "Tin is a chemical element with the symbol Sn and atomic number 50." },
  { num: 51, symbol: "Sb", name: "Antimony", mass: "121.76", category: "metalloid", x: 15, y: 5, config: "[Kr] 4d10 5s2 5p3", desc: "Antimony is a chemical element with the symbol Sb and atomic number 51." },
  { num: 52, symbol: "Te", name: "Tellurium", mass: "127.60", category: "metalloid", x: 16, y: 5, config: "[Kr] 4d10 5s2 5p4", desc: "Tellurium is a chemical element with the symbol Te and atomic number 52." },
  { num: 53, symbol: "I", name: "Iodine", mass: "126.90", category: "halogen", x: 17, y: 5, config: "[Kr] 4d10 5s2 5p5", desc: "Iodine is a chemical element with the symbol I and atomic number 53." },
  { num: 54, symbol: "Xe", name: "Xenon", mass: "131.29", category: "noble-gas", x: 18, y: 5, config: "[Kr] 4d10 5s2 5p6", desc: "Xenon is a chemical element with the symbol Xe and atomic number 54." },
  { num: 55, symbol: "Cs", name: "Caesium", mass: "132.91", category: "alkali-metal", x: 1, y: 6, config: "[Xe] 6s1", desc: "Caesium is a chemical element with the symbol Cs and atomic number 55." },
  { num: 56, symbol: "Ba", name: "Barium", mass: "137.33", category: "alkaline-earth", x: 2, y: 6, config: "[Xe] 6s2", desc: "Barium is a chemical element with the symbol Ba and atomic number 56." },
  // Lanthanides map to y: 9, start at x: 4. Actinides map to y: 10, start at x: 4.
  // Wait, standard periodic table puts 57-71 in row 8 (lanthanides standalone).
  { num: 57, symbol: "La", name: "Lanthanum", mass: "138.91", category: "lanthanide", x: 4, y: 9, config: "[Xe] 5d1 6s2", desc: "Lanthanum is a chemical element with the symbol La and atomic number 57." },
  { num: 58, symbol: "Ce", name: "Cerium", mass: "140.12", category: "lanthanide", x: 5, y: 9, config: "[Xe] 4f1 5d1 6s2", desc: "Cerium is a chemical element with the symbol Ce and atomic number 58." },
  { num: 59, symbol: "Pr", name: "Praseodymium", mass: "140.91", category: "lanthanide", x: 6, y: 9, config: "[Xe] 4f3 6s2", desc: "Praseodymium is a chemical element with the symbol Pr and atomic number 59." },
  { num: 60, symbol: "Nd", name: "Neodymium", mass: "144.24", category: "lanthanide", x: 7, y: 9, config: "[Xe] 4f4 6s2", desc: "Neodymium is a chemical element with the symbol Nd and atomic number 60." },
  { num: 61, symbol: "Pm", name: "Promethium", mass: "(145)", category: "lanthanide", x: 8, y: 9, config: "[Xe] 4f5 6s2", desc: "Promethium is a chemical element with the symbol Pm and atomic number 61." },
  { num: 62, symbol: "Sm", name: "Samarium", mass: "150.36", category: "lanthanide", x: 9, y: 9, config: "[Xe] 4f6 6s2", desc: "Samarium is a chemical element with the symbol Sm and atomic number 62." },
  { num: 63, symbol: "Eu", name: "Europium", mass: "151.96", category: "lanthanide", x: 10, y: 9, config: "[Xe] 4f7 6s2", desc: "Europium is a chemical element with the symbol Eu and atomic number 63." },
  { num: 64, symbol: "Gd", name: "Gadolinium", mass: "157.25", category: "lanthanide", x: 11, y: 9, config: "[Xe] 4f7 5d1 6s2", desc: "Gadolinium is a chemical element with the symbol Gd and atomic number 64." },
  { num: 65, symbol: "Tb", name: "Terbium", mass: "158.93", category: "lanthanide", x: 12, y: 9, config: "[Xe] 4f9 6s2", desc: "Terbium is a chemical element with the symbol Tb and atomic number 65." },
  { num: 66, symbol: "Dy", name: "Dysprosium", mass: "162.50", category: "lanthanide", x: 13, y: 9, config: "[Xe] 4f10 6s2", desc: "Dysprosium is a chemical element with the symbol Dy and atomic number 66." },
  { num: 67, symbol: "Ho", name: "Holmium", mass: "164.93", category: "lanthanide", x: 14, y: 9, config: "[Xe] 4f11 6s2", desc: "Holmium is a chemical element with the symbol Ho and atomic number 67." },
  { num: 68, symbol: "Er", name: "Erbium", mass: "167.26", category: "lanthanide", x: 15, y: 9, config: "[Xe] 4f12 6s2", desc: "Erbium is a chemical element with the symbol Er and atomic number 68." },
  { num: 69, symbol: "Tm", name: "Thulium", mass: "168.93", category: "lanthanide", x: 16, y: 9, config: "[Xe] 4f13 6s2", desc: "Thulium is a chemical element with the symbol Tm and atomic number 69." },
  { num: 70, symbol: "Yb", name: "Ytterbium", mass: "173.05", category: "lanthanide", x: 17, y: 9, config: "[Xe] 4f14 6s2", desc: "Ytterbium is a chemical element with the symbol Yb and atomic number 70." },
  { num: 71, symbol: "Lu", name: "Lutetium", mass: "174.97", category: "lanthanide", x: 18, y: 9, config: "[Xe] 4f14 5d1 6s2", desc: "Lutetium is a chemical element with the symbol Lu and atomic number 71." },
  { num: 72, symbol: "Hf", name: "Hafnium", mass: "178.49", category: "transition-metal", x: 4, y: 6, config: "[Xe] 4f14 5d2 6s2", desc: "Hafnium is a chemical element with the symbol Hf and atomic number 72." },
  { num: 73, symbol: "Ta", name: "Tantalum", mass: "180.95", category: "transition-metal", x: 5, y: 6, config: "[Xe] 4f14 5d3 6s2", desc: "Tantalum is a chemical element with the symbol Ta and atomic number 73." },
  { num: 74, symbol: "W", name: "Tungsten", mass: "183.84", category: "transition-metal", x: 6, y: 6, config: "[Xe] 4f14 5d4 6s2", desc: "Tungsten is a chemical element with the symbol W and atomic number 74." },
  { num: 75, symbol: "Re", name: "Rhenium", mass: "186.21", category: "transition-metal", x: 7, y: 6, config: "[Xe] 4f14 5d5 6s2", desc: "Rhenium is a chemical element with the symbol Re and atomic number 75." },
  { num: 76, symbol: "Os", name: "Osmium", mass: "190.23", category: "transition-metal", x: 8, y: 6, config: "[Xe] 4f14 5d6 6s2", desc: "Osmium is a chemical element with the symbol Os and atomic number 76." },
  { num: 77, symbol: "Ir", name: "Iridium", mass: "192.22", category: "transition-metal", x: 9, y: 6, config: "[Xe] 4f14 5d7 6s2", desc: "Iridium is a chemical element with the symbol Ir and atomic number 77." },
  { num: 78, symbol: "Pt", name: "Platinum", mass: "195.08", category: "transition-metal", x: 10, y: 6, config: "[Xe] 4f14 5d9 6s1", desc: "Platinum is a chemical element with the symbol Pt and atomic number 78." },
  { num: 79, symbol: "Au", name: "Gold", mass: "196.97", category: "transition-metal", x: 11, y: 6, config: "[Xe] 4f14 5d10 6s1", desc: "Gold is a chemical element with the symbol Au and atomic number 79." },
  { num: 80, symbol: "Hg", name: "Mercury", mass: "200.59", category: "transition-metal", x: 12, y: 6, config: "[Xe] 4f14 5d10 6s2", desc: "Mercury is a chemical element with the symbol Hg and atomic number 80." },
  { num: 81, symbol: "Tl", name: "Thallium", mass: "204.38", category: "post-transition", x: 13, y: 6, config: "[Xe] 4f14 5d10 6s2 6p1", desc: "Thallium is a chemical element with the symbol Tl and atomic number 81." },
  { num: 82, symbol: "Pb", name: "Lead", mass: "207.2", category: "post-transition", x: 14, y: 6, config: "[Xe] 4f14 5d10 6s2 6p2", desc: "Lead is a chemical element with the symbol Pb and atomic number 82." },
  { num: 83, symbol: "Bi", name: "Bismuth", mass: "208.98", category: "post-transition", x: 15, y: 6, config: "[Xe] 4f14 5d10 6s2 6p3", desc: "Bismuth is a chemical element with the symbol Bi and atomic number 83." },
  { num: 84, symbol: "Po", name: "Polonium", mass: "(209)", category: "metalloid", x: 16, y: 6, config: "[Xe] 4f14 5d10 6s2 6p4", desc: "Polonium is a chemical element with the symbol Po and atomic number 84." },
  { num: 85, symbol: "At", name: "Astatine", mass: "(210)", category: "halogen", x: 17, y: 6, config: "[Xe] 4f14 5d10 6s2 6p5", desc: "Astatine is a chemical element with the symbol At and atomic number 85." },
  { num: 86, symbol: "Rn", name: "Radon", mass: "(222)", category: "noble-gas", x: 18, y: 6, config: "[Xe] 4f14 5d10 6s2 6p6", desc: "Radon is a chemical element with the symbol Rn and atomic number 86." },
  { num: 87, symbol: "Fr", name: "Francium", mass: "(223)", category: "alkali-metal", x: 1, y: 7, config: "[Rn] 7s1", desc: "Francium is a chemical element with the symbol Fr and atomic number 87." },
  { num: 88, symbol: "Ra", name: "Radium", mass: "(226)", category: "alkaline-earth", x: 2, y: 7, config: "[Rn] 7s2", desc: "Radium is a chemical element with the symbol Ra and atomic number 88." },
  
  // Actinides map to y: 10, start at x: 4
  { num: 89, symbol: "Ac", name: "Actinium", mass: "(227)", category: "actinide", x: 4, y: 10, config: "[Rn] 6d1 7s2", desc: "Actinium is a chemical element with the symbol Ac and atomic number 89." },
  { num: 90, symbol: "Th", name: "Thorium", mass: "232.04", category: "actinide", x: 5, y: 10, config: "[Rn] 6d2 7s2", desc: "Thorium is a chemical element with the symbol Th and atomic number 90." },
  { num: 91, symbol: "Pa", name: "Protactinium", mass: "231.04", category: "actinide", x: 6, y: 10, config: "[Rn] 5f2 6d1 7s2", desc: "Protactinium is a chemical element with the symbol Pa and atomic number 91." },
  { num: 92, symbol: "U", name: "Uranium", mass: "238.03", category: "actinide", x: 7, y: 10, config: "[Rn] 5f3 6d1 7s2", desc: "Uranium is a chemical element with the symbol U and atomic number 92." },
  { num: 93, symbol: "Np", name: "Neptunium", mass: "(237)", category: "actinide", x: 8, y: 10, config: "[Rn] 5f4 6d1 7s2", desc: "Neptunium is a chemical element with the symbol Np and atomic number 93." },
  { num: 94, symbol: "Pu", name: "Plutonium", mass: "(244)", category: "actinide", x: 9, y: 10, config: "[Rn] 5f6 7s2", desc: "Plutonium is a chemical element with the symbol Pu and atomic number 94." },
  { num: 95, symbol: "Am", name: "Americium", mass: "(243)", category: "actinide", x: 10, y: 10, config: "[Rn] 5f7 7s2", desc: "Americium is a chemical element with the symbol Am and atomic number 95." },
  { num: 96, symbol: "Cm", name: "Curium", mass: "(247)", category: "actinide", x: 11, y: 10, config: "[Rn] 5f7 6d1 7s2", desc: "Curium is a chemical element with the symbol Cm and atomic number 96." },
  { num: 97, symbol: "Bk", name: "Berkelium", mass: "(247)", category: "actinide", x: 12, y: 10, config: "[Rn] 5f9 7s2", desc: "Berkelium is a chemical element with the symbol Bk and atomic number 97." },
  { num: 98, symbol: "Cf", name: "Californium", mass: "(251)", category: "actinide", x: 13, y: 10, config: "[Rn] 5f10 7s2", desc: "Californium is a chemical element with the symbol Cf and atomic number 98." },
  { num: 99, symbol: "Es", name: "Einsteinium", mass: "(252)", category: "actinide", x: 14, y: 10, config: "[Rn] 5f11 7s2", desc: "Einsteinium is a chemical element with the symbol Es and atomic number 99." },
  { num: 100, symbol: "Fm", name: "Fermium", mass: "(257)", category: "actinide", x: 15, y: 10, config: "[Rn] 5f12 7s2", desc: "Fermium is a chemical element with the symbol Fm and atomic number 100." },
  { num: 101, symbol: "Md", name: "Mendelevium", mass: "(258)", category: "actinide", x: 16, y: 10, config: "[Rn] 5f13 7s2", desc: "Mendelevium is a chemical element with the symbol Md and atomic number 101." },
  { num: 102, symbol: "No", name: "Nobelium", mass: "(259)", category: "actinide", x: 17, y: 10, config: "[Rn] 5f14 7s2", desc: "Nobelium is a chemical element with the symbol No and atomic number 102." },
  { num: 103, symbol: "Lr", name: "Lawrencium", mass: "(262)", category: "actinide", x: 18, y: 10, config: "[Rn] 5f14 6d1 7s2", desc: "Lawrencium is a chemical element with the symbol Lr and atomic number 103." },
  
  // Row 7 continued
  { num: 104, symbol: "Rf", name: "Rutherfordium", mass: "(267)", category: "transition-metal", x: 4, y: 7, config: "unknown", desc: "Rutherfordium is a chemical element with the symbol Rf and atomic number 104." },
  { num: 105, symbol: "Db", name: "Dubnium", mass: "(268)", category: "transition-metal", x: 5, y: 7, config: "unknown", desc: "Dubnium is a chemical element with the symbol Db and atomic number 105." },
  { num: 106, symbol: "Sg", name: "Seaborgium", mass: "(269)", category: "transition-metal", x: 6, y: 7, config: "unknown", desc: "Seaborgium is a chemical element with the symbol Sg and atomic number 106." },
  { num: 107, symbol: "Bh", name: "Bohrium", mass: "(270)", category: "transition-metal", x: 7, y: 7, config: "unknown", desc: "Bohrium is a chemical element with the symbol Bh and atomic number 107." },
  { num: 108, symbol: "Hs", name: "Hassium", mass: "(269)", category: "transition-metal", x: 8, y: 7, config: "unknown", desc: "Hassium is a chemical element with the symbol Hs and atomic number 108." },
  { num: 109, symbol: "Mt", name: "Meitnerium", mass: "(278)", category: "unknown", x: 9, y: 7, config: "unknown", desc: "Meitnerium is a chemical element with the symbol Mt and atomic number 109." },
  { num: 110, symbol: "Ds", name: "Darmstadtium", mass: "(281)", category: "unknown", x: 10, y: 7, config: "unknown", desc: "Darmstadtium is a chemical element with the symbol Ds and atomic number 110." },
  { num: 111, symbol: "Rg", name: "Roentgenium", mass: "(282)", category: "unknown", x: 11, y: 7, config: "unknown", desc: "Roentgenium is a chemical element with the symbol Rg and atomic number 111." },
  { num: 112, symbol: "Cn", name: "Copernicium", mass: "(285)", category: "transition-metal", x: 12, y: 7, config: "unknown", desc: "Copernicium is a chemical element with the symbol Cn and atomic number 112." },
  { num: 113, symbol: "Nh", name: "Nihonium", mass: "(286)", category: "unknown", x: 13, y: 7, config: "unknown", desc: "Nihonium is a chemical element with the symbol Nh and atomic number 113." },
  { num: 114, symbol: "Fl", name: "Flerovium", mass: "(289)", category: "post-transition", x: 14, y: 7, config: "unknown", desc: "Flerovium is a chemical element with the symbol Fl and atomic number 114." },
  { num: 115, symbol: "Mc", name: "Moscovium", mass: "(290)", category: "unknown", x: 15, y: 7, config: "unknown", desc: "Moscovium is a chemical element with the symbol Mc and atomic number 115." },
  { num: 116, symbol: "Lv", name: "Livermorium", mass: "(293)", category: "unknown", x: 16, y: 7, config: "unknown", desc: "Livermorium is a chemical element with the symbol Lv and atomic number 116." },
  { num: 117, symbol: "Ts", name: "Tennessine", mass: "(294)", category: "unknown", x: 17, y: 7, config: "unknown", desc: "Tennessine is a chemical element with the symbol Ts and atomic number 117." },
  { num: 118, symbol: "Og", name: "Oganesson", mass: "(294)", category: "unknown", x: 18, y: 7, config: "unknown", desc: "Oganesson is a chemical element with the symbol Og and atomic number 118." }
];
